repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.3
    hooks:
      # Run the Ruff formatter.
      - id: ruff-format
        exclude: (research|model)/.+\.py

      # Run the Ruff linter.
      - id: ruff
        exclude: research/.+\.py
        args: [
          "--fix",
          "--ignore",
          "F401" # ignore unused imports, as these are sometimes used for side effects,
          # e.g. "import torch_neuron"
        ]
