version: '3.8'
services:
  api:
    image: public.ecr.aws/n4g1c9q0/maia/cowd-api:latest
    ports:
      - "8000:8000"
    networks:
      - cow-detect-network
    secrets:
      - aws
    environment:
      AWS_PROFILE: "dvc-user"
      AWS_SHARED_CREDENTIALS_FILE: /run/secrets/aws

  dashboard:
    image: public.ecr.aws/n4g1c9q0/maia/cowd-dashboard:latest
    ports:
      - "8501:8501"
    networks:
      - cow-detect-network
    environment:
      AWS_PROFILE: "dvc-user"
      APISERVICE_BASE_URL: "http://host.docker.internal:8000/api"
      AWS_SHARED_CREDENTIALS_FILE: /run/secrets/aws
    secrets:
      - aws
    extra_hosts:
      - "host.docker.internal:host-gateway"

secrets:
  aws:
    file: ./.aws-credentials

networks:
  cow-detect-network:
    driver: bridge