experiment_name: "faster-rcnn-v2"
num_epochs: 10
sort_paths: true
train_fraction: 1.0
valid_fraction: 0.2
data_loader:
  batch_size: 2
  data_shuffle: true
  num_workers: 0
optimizer:
  learning_rate: 0.005
  momentum: 0.9
  weight_decay: 0.0005