# Toy config for rapid e2e testing, just 1 epoch and very little data
experiment_name: "faster-rcnn-v1"
num_epochs: 1
train_fraction: 0.002
valid_fraction: 0.002
data_loader:
  batch_size: 2
  data_shuffle: true
  num_workers: 0
optimizer:
  learning_rate: 0.005
  momentum: 0.9
  weight_decay: 0.0005