experiment_name: "faster-rcnn-v1"
device: "cpu"
num_epochs: 15
train_fraction: 0.30
valid_fraction: 0.10
data_loader:
  batch_size: 2
  data_shuffle: true
  num_workers: 0
  valid_batch_size: 10
optimizer:
  learning_rate: 0.005
  momentum: 0.9
  weight_decay: 0.0005